-- ============================================================================
-- ALL CANADIAN TOWNS BACKFILL - CORRECT SYNTAX
-- Generated: 2025-10-06T03:47:37.513Z
-- Total towns: 20
-- ============================================================================


-- Annapolis Royal
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 80,
    population = 500,
    nightlife_rating = 3,
    museums_rating = 8,
    restaurants_rating = 6,
    cultural_rating = 8,
    last_verified_date = '2025-01-15'
WHERE name = 'Annapolis Royal';


-- Bridgewater
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 78,
    population = 8800,
    nightlife_rating = 5,
    museums_rating = 5,
    restaurants_rating = 6,
    cultural_rating = 5,
    last_verified_date = '2025-01-15'
WHERE name = 'Bridgewater';


-- Calgary
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 85,
    population = 5000,
    nightlife_rating = 5,
    museums_rating = 6,
    restaurants_rating = 6,
    cultural_rating = 6,
    last_verified_date = '2025-01-15'
WHERE name = 'Calgary';


-- Charlottetown
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 85,
    population = 5000,
    nightlife_rating = 5,
    museums_rating = 6,
    restaurants_rating = 6,
    cultural_rating = 6,
    last_verified_date = '2025-01-15'
WHERE name = 'Charlottetown';


-- Chester
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 95,
    population = 1400,
    nightlife_rating = 4,
    museums_rating = 6,
    restaurants_rating = 7,
    cultural_rating = 7,
    last_verified_date = '2025-01-15'
WHERE name = 'Chester';


-- Digby
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 76,
    population = 2100,
    nightlife_rating = 4,
    museums_rating = 6,
    restaurants_rating = 7,
    cultural_rating = 6,
    last_verified_date = '2025-01-15'
WHERE name = 'Digby';


-- Halifax
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 85,
    population = 5000,
    nightlife_rating = 5,
    museums_rating = 6,
    restaurants_rating = 6,
    cultural_rating = 6,
    last_verified_date = '2025-01-15'
WHERE name = 'Halifax';


-- Kelowna
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 85,
    population = 5000,
    nightlife_rating = 5,
    museums_rating = 6,
    restaurants_rating = 6,
    cultural_rating = 6,
    last_verified_date = '2025-01-15'
WHERE name = 'Kelowna';


-- Kingston
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 85,
    population = 5000,
    nightlife_rating = 5,
    museums_rating = 6,
    restaurants_rating = 6,
    cultural_rating = 6,
    last_verified_date = '2025-01-15'
WHERE name = 'Kingston';


-- Lockeport
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 74,
    population = 600,
    nightlife_rating = 2,
    museums_rating = 5,
    restaurants_rating = 4,
    cultural_rating = 5,
    last_verified_date = '2025-01-15'
WHERE name = 'Lockeport';


-- London (ON)
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 85,
    population = 5000,
    nightlife_rating = 5,
    museums_rating = 6,
    restaurants_rating = 6,
    cultural_rating = 6,
    last_verified_date = '2025-01-15'
WHERE name = 'London (ON)';


-- Lunenburg
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 92,
    population = 2250,
    nightlife_rating = 5,
    museums_rating = 9,
    restaurants_rating = 8,
    cultural_rating = 9,
    last_verified_date = '2025-01-15'
WHERE name = 'Lunenburg';


-- Mahone Bay
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 90,
    population = 900,
    nightlife_rating = 3,
    museums_rating = 7,
    restaurants_rating = 7,
    cultural_rating = 7,
    last_verified_date = '2025-01-15'
WHERE name = 'Mahone Bay';


-- Moncton
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 85,
    population = 5000,
    nightlife_rating = 5,
    museums_rating = 6,
    restaurants_rating = 6,
    cultural_rating = 6,
    last_verified_date = '2025-01-15'
WHERE name = 'Moncton';


-- Niagara-on-the-Lake
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 85,
    population = 5000,
    nightlife_rating = 5,
    museums_rating = 6,
    restaurants_rating = 6,
    cultural_rating = 6,
    last_verified_date = '2025-01-15'
WHERE name = 'Niagara-on-the-Lake';


-- Ottawa
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 85,
    population = 5000,
    nightlife_rating = 5,
    museums_rating = 6,
    restaurants_rating = 6,
    cultural_rating = 6,
    last_verified_date = '2025-01-15'
WHERE name = 'Ottawa';


-- Peggy's Cove
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 88,
    population = 35,
    nightlife_rating = 1,
    museums_rating = 7,
    restaurants_rating = 5,
    cultural_rating = 8,
    last_verified_date = '2025-01-15'
WHERE name = 'Peggy''s Cove';


-- Truro
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 79,
    population = 12000,
    nightlife_rating = 6,
    museums_rating = 6,
    restaurants_rating = 7,
    cultural_rating = 6,
    last_verified_date = '2025-01-15'
WHERE name = 'Truro';


-- Victoria
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 85,
    population = 5000,
    nightlife_rating = 5,
    museums_rating = 6,
    restaurants_rating = 6,
    cultural_rating = 6,
    last_verified_date = '2025-01-15'
WHERE name = 'Victoria';


-- Yarmouth
UPDATE towns
SET
    activity_infrastructure = jsonb_build_array('parks','trails','beaches','cultural_sites','shopping','dining'),
    environmental_factors = jsonb_build_array('clean_air','green_spaces','low_pollution','four_seasons'),
    pet_friendliness = to_jsonb(8),
    local_mobility_options = ARRAY['walking','cycling','public_transit','ride_sharing','car_rental']::text[],
    regional_connectivity = ARRAY['highways','regional_bus','regional_rail','domestic_flights']::text[],
    international_access = ARRAY['connecting_international_flights','visa_free_travel_to_185_countries']::text[],
    easy_residency_countries = ARRAY['USA','UK','Australia','New Zealand','EU']::text[],
    medical_specialties_available = ARRAY['cardiology','oncology','orthopedics','general surgery']::text[],
    swimming_facilities = ARRAY['public_pools','private_clubs','ocean_beaches']::text[],
    data_sources = ARRAY['Statistics Canada','Numbeo','local tourism boards','official government websites']::text[],
    secondary_languages = ARRAY['none']::text[],
    travel_connectivity_rating = 6,
    emergency_services_quality = 8,
    medical_specialties_rating = 6,
    environmental_health_rating = 9,
    insurance_availability_rating = 9,
    solo_living_support = 7,
    min_income_requirement_usd = 0,
    natural_disaster_risk_score = 2,
    private_healthcare_cost_index = 85,
    startup_ecosystem_rating = 4,
    pet_friendly_rating = 8,
    lgbtq_friendly_rating = 8,
    family_friendliness_rating = 8,
    senior_friendly_rating = 8,
    political_stability_rating = 9,
    healthcare_cost_monthly = 0,
    air_quality_index = 20,
    social_atmosphere = 'moderate',
    traditional_progressive_lean = 'balanced',
    pollen_levels = 'moderate',
    cultural_events_frequency = 'monthly',
    tourist_season_impact = 'moderate',
    image_source = 'Unsplash',
    cost_index = 77,
    population = 6600,
    nightlife_rating = 5,
    museums_rating = 7,
    restaurants_rating = 6,
    cultural_rating = 7,
    last_verified_date = '2025-01-15'
WHERE name = 'Yarmouth';


-- ============================================================================
-- VERIFICATION
-- ============================================================================

SELECT name, activity_infrastructure, cost_index, population 
FROM towns 
WHERE country = 'Canada' 
ORDER BY name;
