-- Populate English proficiency data for all towns
-- This is CRITICAL data for retirees to know if they can communicate

-- Default country values
UPDATE towns SET english_proficiency = 95 WHERE country = 'United States';
UPDATE towns SET english_proficiency = 90 WHERE country = 'Canada';
UPDATE towns SET english_proficiency = 98 WHERE country = 'United Kingdom';
UPDATE towns SET english_proficiency = 95 WHERE country = 'Australia';
UPDATE towns SET english_proficiency = 95 WHERE country = 'New Zealand';
UPDATE towns SET english_proficiency = 98 WHERE country = 'Ireland';
UPDATE towns SET english_proficiency = 72 WHERE country = 'Netherlands';
UPDATE towns SET english_proficiency = 68 WHERE country = 'Singapore';
UPDATE towns SET english_proficiency = 60 WHERE country = 'Portugal';
UPDATE towns SET english_proficiency = 35 WHERE country = 'Spain';
UPDATE towns SET english_proficiency = 36 WHERE country = 'Italy';
UPDATE towns SET english_proficiency = 39 WHERE country = 'France';
UPDATE towns SET english_proficiency = 63 WHERE country = 'Germany';
UPDATE towns SET english_proficiency = 35 WHERE country = 'Mexico';
UPDATE towns SET english_proficiency = 52 WHERE country = 'Greece';
UPDATE towns SET english_proficiency = 60 WHERE country = 'Croatia';
UPDATE towns SET english_proficiency = 27 WHERE country = 'Thailand';
UPDATE towns SET english_proficiency = 32 WHERE country = 'Vietnam';
UPDATE towns SET english_proficiency = 89 WHERE country = 'Malta';
UPDATE towns SET english_proficiency = 73 WHERE country = 'Cyprus';
UPDATE towns SET english_proficiency = 68 WHERE country = 'Israel';
UPDATE towns SET english_proficiency = 58 WHERE country = 'India';
UPDATE towns SET english_proficiency = 61 WHERE country = 'South Africa';
UPDATE towns SET english_proficiency = 58 WHERE country = 'Philippines';
UPDATE towns SET english_proficiency = 58 WHERE country = 'Malaysia';
UPDATE towns SET english_proficiency = 62 WHERE country = 'Belize';
UPDATE towns SET english_proficiency = 64 WHERE country = 'Austria';
UPDATE towns SET english_proficiency = 61 WHERE country = 'Belgium';
UPDATE towns SET english_proficiency = 61 WHERE country = 'Switzerland';
UPDATE towns SET english_proficiency = 98 WHERE country = 'Bahamas';
UPDATE towns SET english_proficiency = 98 WHERE country = 'Barbados';
UPDATE towns SET english_proficiency = 90 WHERE country = 'Turks and Caicos';
UPDATE towns SET english_proficiency = 85 WHERE country = 'U.S. Virgin Islands';
UPDATE towns SET english_proficiency = 90 WHERE country = 'Saint Lucia';
UPDATE towns SET english_proficiency = 90 WHERE country = 'Saint Kitts and Nevis';
UPDATE towns SET english_proficiency = 90 WHERE country = 'Saint Vincent and Grenadines';
UPDATE towns SET english_proficiency = 75 WHERE country = 'Sint Maarten';
UPDATE towns SET english_proficiency = 45 WHERE country = 'Saint Martin';
UPDATE towns SET english_proficiency = 65 WHERE country = 'Aruba';
UPDATE towns SET english_proficiency = 50 WHERE country = 'Puerto Rico';
UPDATE towns SET english_proficiency = 35 WHERE country = 'Dominican Republic';
UPDATE towns SET english_proficiency = 45 WHERE country = 'Panama';
UPDATE towns SET english_proficiency = 43 WHERE country = 'Costa Rica';
UPDATE towns SET english_proficiency = 42 WHERE country = 'Chile';
UPDATE towns SET english_proficiency = 45 WHERE country = 'Argentina';
UPDATE towns SET english_proficiency = 41 WHERE country = 'Uruguay';
UPDATE towns SET english_proficiency = 28 WHERE country = 'Brazil';
UPDATE towns SET english_proficiency = 32 WHERE country = 'Colombia';
UPDATE towns SET english_proficiency = 35 WHERE country = 'Ecuador';
UPDATE towns SET english_proficiency = 30 WHERE country = 'Peru';
UPDATE towns SET english_proficiency = 33 WHERE country = 'Turkey';
UPDATE towns SET english_proficiency = 32 WHERE country = 'Morocco';
UPDATE towns SET english_proficiency = 35 WHERE country = 'Tunisia';
UPDATE towns SET english_proficiency = 35 WHERE country = 'Egypt';
UPDATE towns SET english_proficiency = 30 WHERE country = 'Indonesia';
UPDATE towns SET english_proficiency = 23 WHERE country = 'Cambodia';
UPDATE towns SET english_proficiency = 20 WHERE country = 'Laos';
UPDATE towns SET english_proficiency = 30 WHERE country = 'Japan';
UPDATE towns SET english_proficiency = 50 WHERE country = 'South Korea';
UPDATE towns SET english_proficiency = 48 WHERE country = 'Taiwan';
UPDATE towns SET english_proficiency = 55 WHERE country = 'Hong Kong';
UPDATE towns SET english_proficiency = 75 WHERE country = 'United Arab Emirates';
UPDATE towns SET english_proficiency = 59 WHERE country = 'Slovenia';
UPDATE towns SET english_proficiency = 55 WHERE country = 'Latvia';
UPDATE towns SET english_proficiency = 45 WHERE country = 'Mauritius';
UPDATE towns SET english_proficiency = 60 WHERE country = 'Seychelles';
UPDATE towns SET english_proficiency = 30 WHERE country = 'Vanuatu';
UPDATE towns SET english_proficiency = 50 WHERE country = 'Samoa';
UPDATE towns SET english_proficiency = 35 WHERE country = 'Tonga';
UPDATE towns SET english_proficiency = 55 WHERE country = 'Fiji';
UPDATE towns SET english_proficiency = 35 WHERE country = 'Solomon Islands';
UPDATE towns SET english_proficiency = 45 WHERE country = 'Palau';
UPDATE towns SET english_proficiency = 25 WHERE country = 'Nicaragua';
UPDATE towns SET english_proficiency = 25 WHERE country = 'Bolivia';
UPDATE towns SET english_proficiency = 28 WHERE country = 'Paraguay';
UPDATE towns SET english_proficiency = 28 WHERE country = 'Guatemala';
UPDATE towns SET english_proficiency = 27 WHERE country = 'Honduras';
UPDATE towns SET english_proficiency = 28 WHERE country = 'El Salvador';
UPDATE towns SET english_proficiency = 45 WHERE country = 'Namibia';
UPDATE towns SET english_proficiency = 40 WHERE country = 'Botswana';
UPDATE towns SET english_proficiency = 48 WHERE country = 'Ghana';
UPDATE towns SET english_proficiency = 35 WHERE country = 'Rwanda';
UPDATE towns SET english_proficiency = 30 WHERE country = 'Tanzania';
UPDATE towns SET english_proficiency = 35 WHERE country = 'Uganda';
UPDATE towns SET english_proficiency = 25 WHERE country = 'Senegal';
UPDATE towns SET english_proficiency = 30 WHERE country = 'Cape Verde';
UPDATE towns SET english_proficiency = 25 WHERE country = 'Madagascar';
UPDATE towns SET english_proficiency = 47 WHERE country = 'Sri Lanka';
UPDATE towns SET english_proficiency = 35 WHERE country = 'Bangladesh';
UPDATE towns SET english_proficiency = 40 WHERE country = 'Nepal';
UPDATE towns SET english_proficiency = 49 WHERE country = 'Pakistan';
UPDATE towns SET english_proficiency = 45 WHERE country = 'Jordan';
UPDATE towns SET english_proficiency = 48 WHERE country = 'Lebanon';
UPDATE towns SET english_proficiency = 70 WHERE country = 'Qatar';
UPDATE towns SET english_proficiency = 65 WHERE country = 'Bahrain';
UPDATE towns SET english_proficiency = 55 WHERE country = 'Kuwait';
UPDATE towns SET english_proficiency = 46 WHERE country = 'Oman';
UPDATE towns SET english_proficiency = 40 WHERE country = 'Saudi Arabia';
UPDATE towns SET english_proficiency = 28 WHERE country = 'China';
UPDATE towns SET english_proficiency = 25 WHERE country = 'Mongolia';
UPDATE towns SET english_proficiency = 30 WHERE country = 'Kazakhstan';
UPDATE towns SET english_proficiency = 25 WHERE country = 'Uzbekistan';
UPDATE towns SET english_proficiency = 20 WHERE country = 'Guinea-Bissau';
UPDATE towns SET english_proficiency = 32 WHERE country = 'Myanmar';

-- Town-specific overrides for major expat/tourist areas
UPDATE towns SET english_proficiency = 70 WHERE town_name = 'Lisbon';
UPDATE towns SET english_proficiency = 65 WHERE town_name = 'Porto';
UPDATE towns SET english_proficiency = 75 WHERE town_name = 'Cascais';
UPDATE towns SET english_proficiency = 70 WHERE town_name = 'Albufeira';
UPDATE towns SET english_proficiency = 50 WHERE town_name = 'Barcelona';
UPDATE towns SET english_proficiency = 45 WHERE town_name = 'Madrid';
UPDATE towns SET english_proficiency = 55 WHERE town_name = 'Palma de Mallorca';
UPDATE towns SET english_proficiency = 55 WHERE town_name = 'Marbella';
UPDATE towns SET english_proficiency = 60 WHERE town_name = 'Athens';
UPDATE towns SET english_proficiency = 65 WHERE town_name = 'Playa del Carmen';
UPDATE towns SET english_proficiency = 60 WHERE town_name = 'Puerto Vallarta';
UPDATE towns SET english_proficiency = 70 WHERE town_name = 'Lake Chapala (Ajijic)';
UPDATE towns SET english_proficiency = 65 WHERE town_name = 'San Miguel de Allende';
UPDATE towns SET english_proficiency = 40 WHERE town_name = 'Bangkok';
UPDATE towns SET english_proficiency = 45 WHERE town_name = 'Phuket';
UPDATE towns SET english_proficiency = 40 WHERE town_name = 'Chiang Mai';
UPDATE towns SET english_proficiency = 45 WHERE town_name = 'Koh Samui';
UPDATE towns SET english_proficiency = 45 WHERE town_name = 'Paris';
UPDATE towns SET english_proficiency = 50 WHERE town_name = 'Nice';
UPDATE towns SET english_proficiency = 45 WHERE town_name = 'Rome';
UPDATE towns SET english_proficiency = 45 WHERE town_name = 'Florence';
UPDATE towns SET english_proficiency = 85 WHERE town_name = 'Dubai';
UPDATE towns SET english_proficiency = 80 WHERE town_name = 'Abu Dhabi';