-- Add description to id column to warn users it's auto-generated and not editable
-- This will show up in Supabase Database Management UI

COMMENT ON COLUMN public.towns.id IS 'Primary key (UUID) - Auto-generated by database. NOT EDITABLE. Used for unique town identification.';
