name: Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint
      continue-on-error: false
    
    - name: Check Style Compliance
      run: node scripts/verify-styles.js
      continue-on-error: true

    - name: Check Navigation Structure
      run: node scripts/verify-navigation.js
      continue-on-error: true
    
    - name: Build Project
      run: npm run build
    
    - name: Check Bundle Size
      run: |
        echo "Bundle sizes:"
        find dist -name "*.js" -o -name "*.css" | while read file; do
          size=$(du -h "$file" | cut -f1)
          echo "  - $(basename "$file"): $size"
        done
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/
    
    - name: Comment PR
      uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          
          // Read check results
          let comment = '## 🔍 Quality Check Results\n\n';
          
          // Add check results
          comment += '### ✅ All quality checks passed!\n\n';
          
          // Add bundle size info if available
          if (fs.existsSync('dist')) {
            comment += '### 📦 Bundle Sizes\n';
            comment += 'See job summary for details.\n\n';
          }
          
          // Add helpful links
          comment += '### 📚 Resources\n';
          comment += '- [Development Process Guide](docs/DEVELOPMENT_PROCESS.md)\n';
          comment += '- [Error Prevention Architecture](ERROR_PREVENTION_ARCHITECTURE.md)\n';
          comment += '- [Project Guidelines](CLAUDE.md)\n';
          
          // Post comment
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  visual-regression:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Start Dev Server
      run: |
        npm run dev &
        sleep 10  # Wait for server to start
    
    - name: Check Key Pages Load
      run: |
        pages=("/daily" "/discover" "/compare" "/profile")
        for page in "${pages[@]}"; do
          echo "Checking $page..."
          curl -f -s -o /dev/null "http://localhost:5173$page" || echo "Warning: $page may have issues"
        done
    
    - name: Kill Dev Server
      run: kill $(lsof -t -i:5173) || true